[s4c_weather]
coldPath = $SPLUNK_DB/s4c_weather/colddb
homePath = $SPLUNK_DB/s4c_weather/db
thawedPath = $SPLUNK_DB/s4c_weather/thaweddb

[s4c_stock_indices]
coldPath = $SPLUNK_DB/s4c_stock_indices/colddb
homePath = $SPLUNK_DB/s4c_stock_indices/db
thawedPath = $SPLUNK_DB/s4c_stock_indices/thaweddb
frozenTimePeriodInSecs = 378691200

[s4c_tutorial]
coldPath = $SPLUNK_DB/s4c_tutorial/colddb
homePath = $SPLUNK_DB/s4c_tutorial/db
thawedPath = $SPLUNK_DB/s4c_tutorial/thaweddb

[s4c_meteo]
coldPath = $SPLUNK_DB/s4c_meteo/colddb
homePath = $SPLUNK_DB/s4c_meteo/db
thawedPath = $SPLUNK_DB/s4c_meteo/thaweddb

[s4c_meteo_metrics]
coldPath = $SPLUNK_DB/s4c_meteo_metrics/colddb
datatype = metric
homePath = $SPLUNK_DB/s4c_meteo_metrics/db
thawedPath = $SPLUNK_DB/s4c_meteo_metrics/thaweddb

[s4c_phyphox]
coldPath = $SPLUNK_DB/s4c_phyphox/colddb
homePath = $SPLUNK_DB/s4c_phyphox/db
thawedPath = $SPLUNK_DB/s4c_phyphox/thaweddb

[s4c_phyphox_metrics]
coldPath = $SPLUNK_DB/s4c_phyphox_metrics/colddb
datatype = metric
homePath = $SPLUNK_DB/s4c_phyphox_metrics/db
thawedPath = $SPLUNK_DB/s4c_phyphox_metrics/thaweddb

[s4c_www]
coldPath = $SPLUNK_DB/s4c_www/colddb
homePath = $SPLUNK_DB/s4c_www/db
thawedPath = $SPLUNK_DB/s4c_www/thaweddb

[s4c_meteo_historic]
coldPath = $SPLUNK_DB/s4c_meteo_historic/colddb
homePath = $SPLUNK_DB/s4c_meteo_historic/db
thawedPath = $SPLUNK_DB/s4c_meteo_historic/thaweddb
frozenTimePeriodInSecs = 378691200

[s4c_student_metrics]
coldPath = $SPLUNK_DB/s4c_student_metrics/colddb
datatype = metric
homePath = $SPLUNK_DB/s4c_student_metrics/db
thawedPath = $SPLUNK_DB/s4c_student_metrics/thaweddb
