[http://phyphox]
disabled = 0
index = s4c_phyphox
indexes = s4c_phyphox
sourcetype = phyphox_json
allowQueryStringAuth = true
token = aaaaa-1111111-2222222-4444-1234567

[http://phyphox_metrics]
disabled = 0
index = s4c_phyphox_metrics
indexes = s4c_phyphox_metrics
sourcetype = phyphox_metrics
allowQueryStringAuth = true
token = bbbbb-1111111-2222222-5555-1234567


[monitor://$SPLUNK_HOME/etc/apps/splunk4champions2/static/gdax_download*]
sourcetype=s4c:quotes
index=s4c_stocks
disabled = false

[monitor://$SPLUNK_HOME/etc/apps/splunk4champions2/static/meteo_historic.csv]
sourcetype = s4c:meteo:historic
index = s4c_meteo_historic
disabled = false

[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/update_stocks.py]
python.version = python3
disabled = false
interval = 86400
index = s4c_stocks
sourcetype = s4c:stocks:json
source = update_stocks

[monitor://$SPLUNK_HOME/etc/apps/splunk4champions2/static/current*]
sourcetype=s4c:weather
index=s4c_weather
disabled = false

[monitor://$SPLUNK_HOME/etc/apps/splunk4champions2/static/www*]
disabled = false
sourcetype = access_combined
host = webgurke
index = s4c_www

[monitor://$SPLUNK_HOME/etc/apps/splunk4champions2/static/tutorialdata.zip]
disabled = false
host_segment = 1
index = s4c_tutorial


[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/download_weatherdata.py]
python.version = python3
disabled = false
index = _internal
interval = -1
source = s4c-weather-script
sourcetype = splunk4champions2:setup

[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/download_weatherdata24.py]
python.version = python3
disabled = false
index = _internal
interval = -1
source = s4c-weather24-script
sourcetype = splunk4champions2:setup

[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/download_wwwdata.py]
python.version = python3
disabled = false
index = _internal
interval = -1
source = s4c-www-script
sourcetype = splunk4champions2:setup

[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/update_wwwdata.py]
python.version = python3
disabled = false
index = _internal
interval = 60
source = s4c-www_live-script
sourcetype = splunk4champions2:setup

[script://$SPLUNK_HOME/etc/apps/splunk4champions2/bin/download_tutorialdata.py]
python.version = python3
disabled = false
index = _internal
interval = -1
source = s4c-tutorial-script
sourcetype = splunk4champions2:setup

[script://./bin/open_meteo_weather.py metrics]
disabled   = 0
interval   = 300
index      = s4c_meteo_metrics
sourcetype = open_meteo:weather:metric
source     = open-meteo
host       = $decideOnStartup

[script://./bin/open_meteo_weather.py events]
disabled   = 0
interval   = 300
index      = s4c_meteo
sourcetype = open_meteo:weather:json
source     = open-meteo
host       = $decideOnStartup